#!/bin/bash

CUSTOMER_FILE_COUNT=`ls /tmp | wc -l`
DEMAND_FILE_COUNT=`ls /tmp | wc -l`
ID_RELATION_FILE_COUNT=`ls /tmp | wc -l`
CLAIM_FILE_COUNT=`ls /tmp | wc -l`
LATEST_MODEL_FILE_COUNT=`ls /tmp | wc -l`
PRICE_BY_CUSTOMER_FILE_COUNT=`ls /tmp | wc -l`
SALES_SUMMARY_CUSTOMER_FILE_COUNT=`ls /tmp | wc -l`


echo $CUSTOMER_FILE_COUNT
echo $DEMAND_FILE_COUNT

echo $ID_RELATION_FILE_COUNT
echo $CLAIM_FILE_COUNT
echo $LATEST_MODEL_FILE_COUNT
echo $PRICE_BY_CUSTOMER_FILE_COUNT
echo $SALES_SUMMARY_CUSTOMER_FILE_COUNT
